[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=Xvfb :0 -screen 0 1280x720x24 -ac +extension GLX +extension RENDER -noreset
autorestart=true
priority=1

[program:openbox]
command=openbox
environment=DISPLAY=":0"
autorestart=true
priority=2

[program:kasmvnc]
command=kasmvncserver :0 -Port 8443 -RectThreads 4 -WebP -FrameRate 60 -sslOnly 0 -disableBasicAuth
environment=DISPLAY=":0"
autorestart=true
priority=3
